### ISSUE TITLE
Update save indicator for global setting changes

### ISSUE THREAD

**Issue by pumbas600** [franomai/cornercutter#41]
Currently, the save indicator on the Frontend (See screenshot below) only updates when you make a change to the selected mod. Ideally, this should also update if you enable/disable a mod or change any of the global settings.

![image](https://user-images.githubusercontent.com/38820160/194038660-6ea1bdf4-90f9-4af5-b33e-36fc22f294b0.png)

**Tasks:**

- [ ] Add global settings thunk in saving slice
- [ ] Migrate current saving to use newly created thunk

**Comment by franomai** [comment]
Just leaving a note here, maybe double check for typos ala '1 hours' for this save prompt, if that's not covered in another ticket.
